kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: sonar
  labels:
    app: postgres
  annotations:
    volume.beta.kubernetes.io/storage-class: csi-ceph-rbd
    volume.beta.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi