apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: nginx-backup
  namespace: velero
spec:
  schedule: "@every 1h"
  template:
    hooks: {}
    includedNamespaces:
      - nginx-example
    ttl: 720h0m0s
