kind: Namespace
apiVersion: v1
metadata:
  name: test-storage
  labels:
    istio-injection: enabled
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs-pvc
  namespace: test-storage
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-ceph-pvc
  namespace: test-storage
spec:
  storageClassName: csi-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
