apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: test-nfs-pod
          image: gcr.io/google_containers/busybox:1.24
          command:
            - "/bin/sh"
          args:
            - "-c"
            - "touch /mnt/SUCCESS && exit 0 || exit 1"
          volumeMounts:
            - name: nfs-pvc
              mountPath: "/mnt"
        - name: test-ceph-pod
          image: gcr.io/google_containers/busybox:1.24
          command:
            - "/bin/sh"
          args:
            - "-c"
            - "touch /mnt/SUCCESS && exit 0 || exit 1"
          volumeMounts:
            - name: ceph-pvc
              mountPath: "/mnt"
      containers:
        - name: nginx
          image: nginx:1.17.6
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/lib/nginx/
              name: nginx-pvc
      volumes:
        - name: nginx-pvc
          persistentVolumeClaim:
            claimName: nginx-pvc
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: test-nfs-pvc
        - name: ceph-pvc
          persistentVolumeClaim:
            claimName: test-ceph-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx-example
spec:
  storageClassName: csi-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs-pvc
  namespace: nginx-example
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-ceph-pvc
  namespace: nginx-example
spec:
  storageClassName: csi-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
  namespace: nginx-example
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9376
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: nginx-vs
  namespace: nginx-example
spec:
  gateways:
    - istio-system/default
    - mesh
  hosts:
    - nginx-svc.nginx-example.svc.cluster.local
    - nginx.127-0-0-1.nip.io
  http:
    - route:
        - destination:
            host: nginx-svc.nginx-example.svc.cluster.local
            port:
              number: 9376
