{
 "title": "TWCC - BAAS - k6 Auto Testing Results",
 "description": "This Dashboard build by asuscloud_justin",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "influxdb" },
   {
    "name": "TestGroup",
    "query": "SHOW TAG VALUES FROM \"successRate\" WITH KEY = \"TestGroup\""
   },
   {
    "name": "TestName",
    "query": "SHOW TAG VALUES FROM \"successRate\" WITH KEY = \"TestName\""
   },
   {
    "name": "URL",
    "label": "URL",
    "query": "SHOW TAG VALUES FROM \"http_req_duration\" WITH KEY = \"name\""
   },
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_looking_up,http_req_receiving,http_req_sending,http_req_waiting"
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "### TWCC Baas Auto-Testing Result\n\nK6 collects metrics for several phases during the HTTP request lifetime.\n\nSuccess Rate is depends on each `TestGroup` and `TestName`\n\nThe combined delays for the application and network (send, wait, recieve) are available in this metric:\n  * **http_req_duration** : \n    * Total time for request, excluding time spent blocked (http_req_blocked), DNS lookup (http_req_looking_up) and TCP connect (http_req_connecting) time. )\n\nThis metric can also be broken down into these metrics:\n  * **http_req_tls_handshaking** :   _(Time spent handshaking TLS session with remote host.)_\n  * **http_req_sending** : _( Time spent sending data to remote host.  )_\n  * **http_req_waiting**      _( Time spent waiting for response from remote host (a.k.a. \"time to first byte\", or \"TTFB\"). )_\n  * **http_req_receiving**       _( Time spent receiving response data from remote host. )_\n\nThese metrics measure delays and durations on the client:\n\n  * **http_req_blocked**     _( Time spent blocked (waiting for a free TCP connection slot) before initiating request.  )_\n  * **http_req_looking_up**     _( Time spent looking up remote host name in DNS. )_\n  * **http_req_connecting**     _( Time spent establishing TCP connection to remote host. )_\n\n\n### View Source Code from Gitea: \n  - [https://gitea-6f1861e5.baas.tmpstg.twcc.tw/TWCC-BAAS/auto-testing-scripts][1]\n\n\n[1]: https://gitea-6f1861e5.baas.tmpstg.twcc.tw/TWCC-BAAS/auto-testing-scripts\n\n"
     },
     "content": "### To choose which measurements to show, use the **Measurements** drop-down in the top left corner!\n\nK6 collects metrics for several phases during the HTTP request lifetime.\n\nThe combined delays for the application and network (send, wait, recieve) are available in this metric:\n  * **http_req_duration**       _( Total time for request, excluding time spent blocked (http_req_blocked), DNS lookup (http_req_looking_up) and TCP connect (http_req_connecting) time. )_\n\nThis metric can also be broken down into these metrics:\n  * **http_req_tls_handshaking**     _( Time spent handshaking TLS session with remote host. )_\n  * **http_req_sending**      _( Time spent sending data to remote host.  )_\n  * **http_req_waiting**      _( Time spent waiting for response from remote host (a.k.a. \"time to first byte\", or \"TTFB\"). )_\n  * **http_req_receiving**       _( Time spent receiving response data from remote host. )_\n\nThese metrics measure delays and durations on the client:\n\n  * **http_req_blocked**     _( Time spent blocked (waiting for a free TCP connection slot) before initiating request.  )_\n  * **http_req_looking_up**     _( Time spent looking up remote host name in DNS. )_\n  * **http_req_connecting**     _( Time spent establishing TCP connection to remote host. )_\n\n\n### View official K6.io documentation here: [https://docs.k6.io/docs/result-metrics][1]\n\n\n[1]: https://docs.k6.io/docs/result-metrics\n\n"
    }
   ]
  },
  { "title": "Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$TestName Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 2 },
   "repeat": "TestName",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$TestName",
     "groupBy": [
      { "params": [ "/^$TestGroup$/" ], "type": "tag" }
     ],
     "measurement": "successRate",
     "query": "SELECT last(\"value\") FROM \"successRate\" WHERE (\"TestGroup\" =~ /^$TestGroup$/ AND \"TestName\" =~ /^$TestName$/) AND $timeFilter GROUP BY \"/^$TestGroup$/\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "$TestName Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$TestName",
     "groupBy": [
      { "params": [ "/^$TestGroup$/" ], "type": "tag" }
     ],
     "measurement": "successRate",
     "query": "SELECT last(\"value\") FROM \"successRate\" WHERE (\"TestGroup\" =~ /^$TestGroup$/ AND \"TestName\" =~ /^$TestName$/) AND $timeFilter GROUP BY \"/^$TestGroup$/\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "$TestName Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$TestName",
     "groupBy": [
      { "params": [ "/^$TestGroup$/" ], "type": "tag" }
     ],
     "measurement": "successRate",
     "query": "SELECT last(\"value\") FROM \"successRate\" WHERE (\"TestGroup\" =~ /^$TestGroup$/ AND \"TestName\" =~ /^$TestName$/) AND $timeFilter GROUP BY \"/^$TestGroup$/\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "$TestName Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$TestName",
     "groupBy": [
      { "params": [ "/^$TestGroup$/" ], "type": "tag" }
     ],
     "measurement": "successRate",
     "query": "SELECT last(\"value\") FROM \"successRate\" WHERE (\"TestGroup\" =~ /^$TestGroup$/ AND \"TestName\" =~ /^$TestName$/) AND $timeFilter GROUP BY \"/^$TestGroup$/\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "$TestName Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$TestName",
     "groupBy": [
      { "params": [ "/^$TestGroup$/" ], "type": "tag" }
     ],
     "measurement": "successRate",
     "query": "SELECT last(\"value\") FROM \"successRate\" WHERE (\"TestGroup\" =~ /^$TestGroup$/ AND \"TestName\" =~ /^$TestName$/) AND $timeFilter GROUP BY \"/^$TestGroup$/\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "$TestName Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$TestName",
     "groupBy": [
      { "params": [ "/^$TestGroup$/" ], "type": "tag" }
     ],
     "measurement": "successRate",
     "query": "SELECT last(\"value\") FROM \"successRate\" WHERE (\"TestGroup\" =~ /^$TestGroup$/ AND \"TestName\" =~ /^$TestName$/) AND $timeFilter GROUP BY \"/^$TestGroup$/\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "$TestName Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$TestName",
     "groupBy": [
      { "params": [ "/^$TestGroup$/" ], "type": "tag" }
     ],
     "measurement": "successRate",
     "query": "SELECT last(\"value\") FROM \"successRate\" WHERE (\"TestGroup\" =~ /^$TestGroup$/ AND \"TestName\" =~ /^$TestName$/) AND $timeFilter GROUP BY \"/^$TestGroup$/\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "$TestName Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$TestName",
     "groupBy": [
      { "params": [ "/^$TestGroup$/" ], "type": "tag" }
     ],
     "measurement": "successRate",
     "query": "SELECT last(\"value\") FROM \"successRate\" WHERE (\"TestGroup\" =~ /^$TestGroup$/ AND \"TestName\" =~ /^$TestName$/) AND $timeFilter GROUP BY \"/^$TestGroup$/\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "$TestName Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$TestName",
     "groupBy": [
      { "params": [ "/^$TestGroup$/" ], "type": "tag" }
     ],
     "measurement": "successRate",
     "query": "SELECT last(\"value\") FROM \"successRate\" WHERE (\"TestGroup\" =~ /^$TestGroup$/ AND \"TestName\" =~ /^$TestName$/) AND $timeFilter GROUP BY \"/^$TestGroup$/\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  { "title": "K6 Test overview (all URLs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "URLs and 95p latency",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "check" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
      { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "errors",
     "query": "SELECT count(\"value\") FROM \"errors\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "Measurement",
   "collapsed": true,
   "panels": [
    {
     "title": "$Measurement (mean)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (max)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (med)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (min)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p90)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p95)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "graph",
     "description": "Grouped by 1 sec intervals",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" },
        { "condition": "AND", "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
        { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
       ]
      },
      {
       "alias": "p90",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$Measurement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Measurement (mean)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (max)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (med)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (min)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p90)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p95)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "graph",
     "description": "Grouped by 1 sec intervals",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" },
        { "condition": "AND", "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
        { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
       ]
      },
      {
       "alias": "p90",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$Measurement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Measurement (mean)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (max)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (med)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (min)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p90)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p95)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "graph",
     "description": "Grouped by 1 sec intervals",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" },
        { "condition": "AND", "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
        { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
       ]
      },
      {
       "alias": "p90",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$Measurement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Measurement (mean)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (max)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (med)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (min)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p90)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p95)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "graph",
     "description": "Grouped by 1 sec intervals",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" },
        { "condition": "AND", "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
        { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
       ]
      },
      {
       "alias": "p90",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$Measurement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Measurement (mean)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (max)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (med)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (min)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p90)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p95)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "graph",
     "description": "Grouped by 1 sec intervals",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" },
        { "condition": "AND", "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
        { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
       ]
      },
      {
       "alias": "p90",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$Measurement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Measurement (mean)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (max)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (med)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (min)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p90)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p95)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "graph",
     "description": "Grouped by 1 sec intervals",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" },
        { "condition": "AND", "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
        { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
       ]
      },
      {
       "alias": "p90",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$Measurement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Measurement (mean)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (max)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (med)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (min)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p90)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p95)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "graph",
     "description": "Grouped by 1 sec intervals",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" },
        { "condition": "AND", "key": "TestGroup", "operator": "=~", "value": "/^$TestGroup$/" },
        { "condition": "AND", "key": "TestName", "operator": "=~", "value": "/^$TestName$/" }
       ]
      },
      {
       "alias": "p90",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}