# ==========================================
#  Title:  K6 Docker-compose
#  Author: Justin Hung
#  Date:   19 Feb 2021
#  Status: Finished
#
#  Usage
#  $ docker-compose up -d influxdb grafana
#  $ docker-compose run -v $PWD/samples:/scripts \
#      k6 run /scripts/es6sample.js
# ==========================================

version: "3.8"

services:
  influxdb:
    image: influxdb:latest
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin1234
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./samples:/scripts

networks:
  k6:
  grafana:

volumes:
  grafana-storage: {}
  influxdb-storage: {}
