# ==========================================
#  Title:  K6 Docker-compose
#  Author: Justin Hung
#  Date:   19 Feb 2021
#  Status: Finished
# ==========================================

version: '3.4'

services:
  influxdb:
    image: influxdb:latest
    networks:
      - monitoring-network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - monitoring-network
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  k6:
    image: loadimpact/k6:latest
    networks:
      - monitoring-network
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./samples:/scripts

networks:
  monitoring-network:
    driver: bridge
    
volumes:
  grafana-storage: {}
  influxdb-storage: {}