# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres
#   namespace: sonar
#   labels:
#     app: postgres
# spec:
#   accessModes:       
#     - ReadWriteMany
#   capacity:          
#     storage: 5Gi
#   mountOptions:   #NFS Mount Option
#     - hard 
#     - nfsvers=4.1 #NFS Server version
#   nfs:            #NFS Setting
#     server: nfs-server.sonar.svc.cluster.local
#     path: /nfs/data/postgres
# ---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: sonar
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: postgres