# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: sonarqube
#   namespace: sonar
#   labels:
#     app: sonarqube
# spec:
#   accessModes:       
#     - ReadWriteMany
#   capacity:          
#     storage: 5Gi
#   mountOptions:
#     - hard  
#     - nfsvers=4.1
#   nfs:
#     server: nfs-server.sonar.svc.cluster.local
#     path: /nfs/data/sonarqube
# ---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube
  namespace: sonar
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: sonarqube