kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: sonar
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: postgres