kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: sonar
  labels:
    app: postgres
spec:
  storageClassName: csi-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
