kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitea-gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-gitea
  template:
    metadata:
      labels:
        app: gitea-gitea
    spec:
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-pvc
        - name: gitea-config
          configMap:
            name: gitea-gitea
            defaultMode: 420
      initContainers:
        - name: init
          image: 'gitea/gitea'
          command:
            - /bin/sh
            - '-c'
            - |-
              mkdir -p /datatmp/gitea/conf
              if [ ! -f /datatmp/gitea/conf/app.ini ]; then
                sed "s/MARIADB_PASSWORD/${MARIADB_PASSWORD}/g" < /etc/gitea/app.ini > /datatmp/gitea/conf/app.ini
              fi
          env:
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-mariadb
                  key: mariadb-password
            - name: SCRIPT
              value: |-
                mkdir -p /datatmp/gitea/conf
                if [ ! -f /datatmp/gitea/conf/app.ini ]; then
                  sed "s/MARIADB_PASSWORD/${MARIADB_PASSWORD}/g" < /etc/gitea/app.ini > /datatmp/gitea/conf/app.ini
                fi
          resources: {}
          volumeMounts:
            - name: gitea-data
              mountPath: /datatmp
            - name: gitea-config
              mountPath: /etc/gitea
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: gitea
          image: 'gitea/gitea'
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-mariadb
                  key: mariadb-password
          resources:
            limits:
              cpu: '4'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 2Gi
          volumeMounts:
            - name: gitea-data
              mountPath: /data
            - name: gitea-config
              mountPath: /etc/gitea
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: memcached
          image: 'memcached:1.5.19-alpine'
          command:
            - memcached
            - '-m 64'
            - '-o'
            - modern
            - '-v'
          ports:
            - name: memcache
              containerPort: 11211
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          imagePullPolicy: IfNotPresent
      nodeName: bctcstg01

