kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 8Gi
  hostPath:
    path: /mnt/mariadb
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
