apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: prometheus
spec:
  containers:
    - name: test-container
      image: nginx
      # ports:
      # - containerPort: 80
      # name: http
      volumeMounts:
        - name: ca
          mountPath: /ca
  volumes:
    - name: ca
      configMap:
        name: istio-ca-root-cert
        items:
          - key: root-cert.pem
            path: root-cert.pem
