kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-prometheus-kube-prome-grafana
  namespace: prometheus
spec:
  endpoints:
    - path: /metrics
      port: service
  namespaceSelector:
    matchNames:
      - prometheus
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/name: grafana
