apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sonar-vs
  namespace: sonar
spec:
  hosts:
    - sonar-vs.sonar.svc.cluster.local
    - sonarqube.justin.io
  gateways:
    - istio-system/default
    - mesh
  http:
    - route:
        - destination:
            host: sonar-vs.sonar.svc.cluster.local
            port:
              number: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: sonar
  labels:
    app: sonarqube
spec:
  type: NodePort
  ports:
    - name: server
      port: 9000
      targetPort: 9000
      nodePort: 30550
      protocol: TCP
  selector:
    app: sonarqube
