kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube
  namespace: sonar
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: sonarqube