# ==========================================
#  Title:  Drone CI Docker-compose
#  Author: Justin Hung
#  Date:   28 Aug 2020
#  Status: need to modify args and test
# ==========================================
version: '2'

services:
  drone-server:
    image: drone/drone:1
    container_name: drone-server
    ports:
      - 8081:80
      - 443:443
    volumes:
      - ./:/data
    restart: always
    environment:
      - DRONE_SERVER_HOST=drone.fism.io
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=true
      - DRONE_RUNNER_CAPACITY=5
      - DRONE_RPC_SECRET=drone-secret
      - DRONE_AGENTS_ENABLED=true
      # GitHub Config
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=your-github-client-id
      - DRONE_GITHUB_CLIENT_SECRET=your-github-secret
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

  drone-agent:
    image: drone/agent:1
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=http://drone-server
      - DRONE_RPC_SECRET=drone-secret
      - DRONE_RUNNER_CAPACITY=3
  
  drone-runner:

    image: drone/drone-runner-docker:1
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 將本機docker的sock mount給內部docker
    environment:
    - DRONE_RPC_HOST=xxxx.ngrok.io # 指定Drone server URL(與drone-server設定一致即可)
    - DRONE_RPC_PROTO=https # 指定與Drone server 的連線協議(http || https)
    - DRONE_RPC_SECRET=<上面server設定的SECRET> # PRC連線密鑰(須與drone-server設定一致)
    - DRONE_RUNNER_CAPACITY=3 # 可以同時執行的任務數
    - DRONE_LOGS_TRACE=true # 開啟日誌
    - DRONE_RUNNER_NAME=dev_depoly #Optional string value. Sets the name of the runner