# ==========================================
#  Title:  Gitea Docker-compose
#  Author: Justin Hung
#  Date:   4 Sep 2020
#  Status: Finished
# ==========================================
version: "3.8"

services:
  gitea-server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=gitea-db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    networks:
      - gitea
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      
  gitea-db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  gitea:

volumes:
  gitea:
  postgres:
