apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-argocd
spec:
  destination:
    name: ''
    namespace: training
    server: 'https://kubernetes.default.svc'
  source:
    path: tb001/deploy
    repoURL: 'https://gitea-6f1861e5.baas.tmpstg.twcc.tw/TWCC-BAAS/training-box.git'
    targetRevision: HEAD
  project: training
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
