kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube
  namespace: sonar
  labels:
    app: sonarqube
spec:
  storageClassName: csi-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
